language: cpp

compiler:
- gcc

addons:
 apt:
  sources:
  - kalakris-cmake
  - ubuntu-toolchain-r-test
  packages:
  - cmake
  - gcc-6
  - g++-6
  - libssl-dev

install:
- mkdir build
- cd build
- git clone https://github.com/miloyip/rapidjson
- ls
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
- ls
- cmake -G "Unix Makefiles" . .. -DRAPIDJSON_INCLUDE=./rapidjson/include
- cmake --build .
