language: cpp

compiler: 
- gcc

install:
- if [ "${CC}" = "gcc" ]; then export TOOLSET="gcc"; ln -s `which g++-6` ${HOME}/bin/g++;
  ln -s `which gcc-6` ${HOME}/bin/gcc; fi

before_script:
- mkdir build
- cd build
- cmake -G "Unix Makefiles" . ..

script:
- cmake --build .

build: cmake --build .

addons:
 apt:
  sources: 
  - kalakris-cmake
  - llvm-toolchain-precise
  - ubuntu-toolchain-r-test
  packages:
  - cmake
  - gcc-6
  - g++-6
  - libgnutls-dev