language: cpp

compiler: 
- gcc

addons:
 apt:
  sources: 
  - kalakris-cmake
  - ubuntu-toolchain-r-test
  packages:
  - cmake
  - gcc-6
  - g++-6
  - libgnutls28-dev
  - libjsoncpp-dev

install:
- mkdir -p ${HOME}/bin
- if [ "${CC}" = "gcc" ]; then export TOOLSET="gcc"; ln -s `which g++-6` ${HOME}/bin/g++;
  ln -s `which gcc-6` ${HOME}/bin/gcc; fi
- export PATH=${HOME}/bin:${PATH}

before_script:
- mkdir build
- cd build
- apt-get download libgnutls28-dev;
- ls ${HOME}
- dpkg -i --force-not-root --root=${HOME} ${HOME}/libgnutls28-dev.deb
- cmake -G "Unix Makefiles" -DGNUTLS_INCLUDE=${HOME}/usr/include/ -DGNUTLS_LIB=${HOME}/usr/lib/x86_64-linux-gnu/ . ..

build: cmake --build .

