 language: cpp

 compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake openssl jsoncpp

 before_script:
   - mkdir build
   - cd build
   - cmake ..

 script: make