# Enable C++ support
language: cpp
# Compiler selection
compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - clang-3.6
          - cmake-3.5
    env: COMPILER=clang++-3.6
compiler: gcc
 addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
          - cmake-3.5
  env: COMPILER=g++-6
# Build steps
script:
  - cmake .
  - make
