language: cpp

compiler: 
- gcc
addons:
 apt:
  sources: kalakris-cmake
  packages: cmake

dist: trusty

before_script:
- mkdir build
- cd build
- cmake --version
- cmake ..

script:
- make

build: make
