language: cpp

compiler: 
- gcc

addons:
 apt:
  sources: 
  - kalakris-cmake
  - ubuntu-toolchain-r-test
  packages:
  - cmake
  - gcc-6
  - g++-6
  - libgnutls28-dev
  - libjsoncpp-dev

install:
- mkdir -p ${HOME}/bin
- if [ "${CC}" = "gcc" ]; then export TOOLSET="gcc"; ln -s `which g++-6` ${HOME}/bin/g++;
  ln -s `which gcc-6` ${HOME}/bin/gcc; fi
- export PATH=${HOME}/bin:${PATH}

before_script:
- mkdir build
- cd build
- cmake -G "Unix Makefiles" . ..

script: cmake --build .
