dist: trusty
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-6
    - g++-6

install:
  - mkdir $HOME/openssl
  - wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
  - tar -xzvf openssl-1.0.2l.tar.gz
  - cd openssl-1.0.2l
  - ./config --prefix=$HOME/openssl/ --openssldir=$HOME/openssl/ --shared
  - make install > /dev/null
  - cd ../
  - mkdir instcpp_build
  - cd instcpp_build
  - git clone https://github.com/miloyip/rapidjson
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

script:
  - cmake -G "Unix Makefiles" . .. -DRAPIDJSON_INCLUDE="$PWD/rapidjson/include/" -DOPENSSL_INCLUDE="$HOME/openssl/include" -DOPENSSL_LIB="$HOME/openssl/lib"
  - cmake --build .