language: cpp

compiler: 
- gcc
addons:
 apt:
  sources: 
  - kalakris-cmake
  - llvm-toolchain-precise
  - ubuntu-toolchain-r-test
  packages:
  - cmake
  - gcc-6
  - g++-6
  - libssl-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi

dist: trusty

before_script:
- mkdir build
- cd build
- cmake ..

script:
- make

build: make
